-- MySQL Script generated by MySQL Workbench
-- Fri Nov 21 10:48:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Coach` (
  `idCoach` INT NOT NULL,
  `Team_idTeam` INT NOT NULL,
  `Firstname` VARCHAR(45) NULL,
  `Lastname` VARCHAR(45) NULL,
  `Startyear` DATE NULL,
  `Endyear` DATE NULL,
  `Experience` INT NULL,
  PRIMARY KEY (`idCoach`, `Team_idTeam`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Game` (
  `idGame` INT NOT NULL,
  `Season_idSeason` INT NOT NULL,
  `Referee_idReferee` INT NOT NULL,
  `Date` DATE NULL,
  `Starttime` TIME NULL,
  `Weather` VARCHAR(45) NULL,
  `Attendance` INT NULL,
  `TotalscoreHome` INT NULL,
  `TotalscoreAway` INT NULL,
  `Stadium_idStadium` INT NOT NULL,
  PRIMARY KEY (`idGame`, `Season_idSeason`),
  INDEX `fk_Game_Season1_idx` (`Season_idSeason` ASC) VISIBLE,
  INDEX `fk_Game_Stadium1_idx` (`Stadium_idStadium` ASC) VISIBLE,
  CONSTRAINT `fk_Game_Season1`
    FOREIGN KEY (`Season_idSeason`)
    REFERENCES `Season` (`idSeason`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_Stadium1`
    FOREIGN KEY (`Stadium_idStadium`)
    REFERENCES `Stadium` (`idStadium`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Game_Team_Stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Game_Team_Stats` (
  `Game_idGame` INT NOT NULL,
  `Team_idTeam` INT NOT NULL,
  `YardsGained` INT NULL,
  `Turnovers` INT NULL,
  `Penalties` INT NULL,
  `PossessionTime` VARCHAR(45) NULL,
  PRIMARY KEY (`Game_idGame`, `Team_idTeam`),
  INDEX `fk_Game_has_Team_Team1_idx` (`Team_idTeam` ASC) VISIBLE,
  INDEX `fk_Game_has_Team_Game_idx` (`Game_idGame` ASC) VISIBLE,
  CONSTRAINT `fk_Game_has_Team_Game`
    FOREIGN KEY (`Game_idGame`)
    REFERENCES `Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Team_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Game_has_Referee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Game_has_Referee` (
  `Game_idGame` INT NOT NULL,
  `Game_Season_idSeason` INT NOT NULL,
  `Referee_idReferee` INT NOT NULL,
  PRIMARY KEY (`Game_idGame`, `Game_Season_idSeason`, `Referee_idReferee`),
  INDEX `fk_Game_has_Referee_Referee1_idx` (`Referee_idReferee` ASC) VISIBLE,
  INDEX `fk_Game_has_Referee_Game1_idx` (`Game_idGame` ASC, `Game_Season_idSeason` ASC) VISIBLE,
  CONSTRAINT `fk_Game_has_Referee_Game1`
    FOREIGN KEY (`Game_idGame` , `Game_Season_idSeason`)
    REFERENCES `Game` (`idGame` , `Season_idSeason`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Game_has_Referee_Referee1`
    FOREIGN KEY (`Referee_idReferee`)
    REFERENCES `Referee` (`idReferee`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Player` (
  `idPlayer` INT NOT NULL,
  `Team_idTeam` INT NOT NULL,
  `Firstname` VARCHAR(45) NULL,
  `Lastname` VARCHAR(45) NULL,
  `JerseyNumber` INT NULL,
  `Position` VARCHAR(45) NULL,
  `Classyear` VARCHAR(45) NULL,
  PRIMARY KEY (`idPlayer`),
  INDEX `fk_Player_Team1_idx` (`Team_idTeam` ASC) VISIBLE,
  CONSTRAINT `fk_Player_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Player_Stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Player_Stats` (
  `Player_idPlayer` INT NOT NULL,
  `Game_idGame` INT NOT NULL,
  `Touchdowns` INT NULL,
  `Yards` INT NULL,
  `Completions` INT NULL,
  `Interceptions` INT NULL,
  `Tackles` INT NULL,
  PRIMARY KEY (`Player_idPlayer`, `Game_idGame`),
  INDEX `fk_Player_has_Game_Game1_idx` (`Game_idGame` ASC) VISIBLE,
  INDEX `fk_Player_has_Game_Player1_idx` (`Player_idPlayer` ASC) VISIBLE,
  CONSTRAINT `fk_Player_has_Game_Player1`
    FOREIGN KEY (`Player_idPlayer`)
    REFERENCES `Player` (`idPlayer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Player_has_Game_Game1`
    FOREIGN KEY (`Game_idGame`)
    REFERENCES `Game` (`idGame`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Referee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Referee` (
  `idReferee` INT NOT NULL,
  `refereename` VARCHAR(45) NULL,
  `experience` VARCHAR(45) NULL,
  `Region` VARCHAR(45) NULL,
  PRIMARY KEY (`idReferee`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Season`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Season` (
  `idSeason` INT NOT NULL,
  `Year` VARCHAR(45) NULL,
  `Startdate` DATE NULL,
  `Enddate` DATE NULL,
  PRIMARY KEY (`idSeason`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Stadium`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Stadium` (
  `idStadium` INT NOT NULL,
  `stadiumname` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `capacity` VARCHAR(45) NULL,
  PRIMARY KEY (`idStadium`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team` (
  `idTeam` INT NOT NULL,
  `Teamname` VARCHAR(45) NULL,
  `Mascot` VARCHAR(45) NULL,
  `Conferene` VARCHAR(45) NULL,
  `Homestadium ID` INT NULL,
  `Coach_idCoach` INT NOT NULL,
  `Coach_Team_idTeam` INT NOT NULL,
  PRIMARY KEY (`idTeam`),
  INDEX `fk_Team_Coach1_idx` (`Coach_idCoach` ASC, `Coach_Team_idTeam` ASC) VISIBLE,
  CONSTRAINT `fk_Team_Coach1`
    FOREIGN KEY (`Coach_idCoach` , `Coach_Team_idTeam`)
    REFERENCES `Coach` (`idCoach` , `Team_idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TeamMatchup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TeamMatchup` (
  `HomeTeamID` INT NOT NULL,
  `AwayTeamID` INT NOT NULL,
  PRIMARY KEY (`HomeTeamID`, `AwayTeamID`),
  INDEX `fk_Team_has_Team_Team2_idx` (`AwayTeamID` ASC) VISIBLE,
  INDEX `fk_Team_has_Team_Team1_idx` (`HomeTeamID` ASC) VISIBLE,
  CONSTRAINT `fk_Team_has_Team_Team1`
    FOREIGN KEY (`HomeTeamID`)
    REFERENCES `Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Team_has_Team_Team2`
    FOREIGN KEY (`AwayTeamID`)
    REFERENCES `Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team_season_performance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Team_season_performance` (
  `Season_idSeason` INT NOT NULL,
  `Team_idTeam` INT NOT NULL,
  `Wins` INT NULL,
  `Losses` INT NULL,
  `Ties` INT NULL,
  `PointsScored` INT NULL,
  `PointsAllowed` INT NULL,
  PRIMARY KEY (`Season_idSeason`, `Team_idTeam`),
  INDEX `fk_Season_has_Team_Team1_idx` (`Team_idTeam` ASC) VISIBLE,
  INDEX `fk_Season_has_Team_Season1_idx` (`Season_idSeason` ASC) VISIBLE,
  CONSTRAINT `fk_Season_has_Team_Season1`
    FOREIGN KEY (`Season_idSeason`)
    REFERENCES `Season` (`idSeason`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Season_has_Team_Team1`
    FOREIGN KEY (`Team_idTeam`)
    REFERENCES `Team` (`idTeam`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
